### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by JayT33** [codingo/Reconnoitre#100]
reconnoitre -t 172.16.243.1-255 --pingsweep -o /root/Desktop/test0
  __
|\"\"\"\-=  RECONNOITRE
(____)      An OSCP scanner by @codingo_

[+] Testing for required utilities on your system.
[#] Performing ping sweep
[!] /root/Desktop/test0 didn't exist and has been created.
[+] Performing ping sweep over 172.16.243.1-255
Traceback (most recent call last):
  File "/usr/local/bin/reconnoitre", line 11, in <module>
    load_entry_point('Reconnoitre==1.0', 'console_scripts', 'reconnoitre')()
  File "/usr/local/lib/python3.7/dist-packages/Reconnoitre-1.0-py3.7.egg/Reconnoitre/reconnoitre.py", line 88, in main
    arguments.quiet)
  File "/usr/local/lib/python3.7/dist-packages/Reconnoitre-1.0-py3.7.egg/Reconnoitre/lib/ping_sweeper.py", line 12, in ping_sweeper
    lines = call_nmap_sweep(target_hosts)
  File "/usr/local/lib/python3.7/dist-packages/Reconnoitre-1.0-py3.7.egg/Reconnoitre/lib/ping_sweeper.py", line 27, in call_nmap_sweep
    lines = str(results).encode("utf-8").split("\n")
TypeError: a bytes-like object is required, not 'str'

**Comment by JayT33** [comment]
using latest build of kali dated 2019-06-20

**Comment by JayT33** [comment]
so i just installed this using python2 setup.py install, and now it will run the above command without issue.

**Comment by finalriposte** [comment]
Interesting, I have the same using python3.  I changed the line to read:
lines = results.split("\n")
and this worked with python3.7.
It's up to @codingo  as to how he wants this to work, but if the goal is python3 compatibility, I'd be happy to make a pull request.

**Comment by codingo** [comment]
@finalriposte is this working on the latest branch? I thought we solved this in #112

**Comment by finalriposte** [comment]
I just did a fresh clone after removing both the Reconnoitre directory and the dist-package in /usr/local/lib and got this:  File "/usr/local/lib/python3.7/dist-packages/Reconnoitre-1.0-py3.7.egg/Reconnoitre/lib/ping_sweeper.py", line 26, in call_nmap_sweep.
TypeError: a bytes-like object is required, not 'str'
Mind you I *am* running python 3.7, but I wouldn't have thought that this would be a big issue.  I can always set up a venv and see if 3.6 works...
