### ISSUE TITLE
snmp_walk.py - TypeError when running --snmp

### ISSUE THREAD

**Issue by jan0sik** [codingo/Reconnoitre#101]
It seems the snmp_walk.py is not working properly because of line 71 to 73 being on separate lines. 
It throws an error: "TypeError: not all arguments converted during string formatting python".
The SCAN variable needs to be encompassed in paranthesis.

`    SCAN = "snmpwalk -c public -v1 %s "
    "1.3.6.1.2.1.25.1.6.0 > '%s%s-systemprocesses.txt'" %
    (ip_address, output_directory, ip_address)`

Needs to become this:

`    SCAN = ("snmpwalk -c public -v1 %s "
    "1.3.6.1.2.1.25.1.6.0 > '%s%s-systemprocesses.txt'" %
    (ip_address, output_directory, ip_address))`

And then snmp works with no issues.
https://github.com/codingo/Reconnoitre/blob/22df8210961fecee47f3c1bd2c036a8849d54984/Reconnoitre/lib/snmp_walk.py#L71-L73

**Comment by codingo** [comment]
Happy to correct this but since you've already explored it, do you want to raise a pull request so it's tied to your account? I don't mind either way.

**Comment by jan0sik** [comment]
This is my first time ever making a pull request, I hope I did it right. There should be a pull request.
