### ISSUE TITLE
program not working on kali

### ISSUE THREAD

**Issue by my-github-user-name** [codingo/Reconnoitre#109]
Traceback (most recent call last):
  File "reconnoitre.py", line 7, in <module>
    from .lib.core.input import CliArgumentParser
ValueError: Attempted relative import in non-package

**Comment by tonydelanuez** [comment]
Did you run `python3 setup.py install`? 

If you install Reconnoitre as a package, you shouldn't run into this error.

**Comment by codingo** [comment]
@tonydelanuez is correct, this will throw if you call it directly. Please follow the instructions on the readme and reply here if you have any further issues and I'll reopen this request.
