### ISSUE TITLE
Provide an option to disable UDP scanning, for faster results and performance

### ISSUE THREAD

**Issue by cwaazywabbit** [codingo/Reconnoitre#31]
UDP could come handy in the OSCP lab/exam, but in real-life scenarios would most likely be blocked or give false-positives.

Providing an option to disable UDP upon wish, would make the tool a bit more suitable for general purposes.

* PS: have already implemented this in my local fork, just waiting for the last pull-request to be approved before I push the new one; if you agree that it could come handy.

Regards

**Comment by codingo** [comment]
Sounds good! Not ignoring your local fork, definitely will have it merged soon. Caught me in an awkward week for testing!
