### ISSUE TITLE
Ping sweep only works with target(s) IPs

### ISSUE THREAD

**Issue by cwaazywabbit** [codingo/Reconnoitre#34]
Hi @codingo,

I came to notice that ping sweep only works with IPs but not with a file that contains a list of IPs/domains.
Yes, one can still use nmap directly, but it would be (perhaps?) nice to have it supported.
All it takes, is a small surgery :)

What do you think?

**Comment by codingo** [comment]
Sure thing, would make it easier for targetting items in scope also.

Do you want to take this or should I?

**Comment by cwaazywabbit** [comment]
Whoever has time for it :)

**Comment by codingo** [comment]
Closed in #49
