### ISSUE TITLE
Issue scanning range-based IP addresses

### ISSUE THREAD

**Issue by cwaazywabbit** [codingo/Reconnoitre#37]
Hi,

during a pentest, I noticed that the tool doesn't take into account the possibility of scanning range-based IP addresses (i.e. 1.1.1.1-100) because, in the end, the parser would output the IP address that was entered on command-line or read from a file. Instead, the parser should extract the IP address from nmap logs so that the findings with correct individual IP addresses are written to file.

![unbenannt](https://user-images.githubusercontent.com/6714156/41900864-ea1026ec-792f-11e8-975f-5835901c39b5.PNG)

**Comment by codingo** [comment]
Hi @cwaazywabbit, sorry for the delay looking into this. Hoping to get some time for this project again soon to work on this.

**Comment by evcsec** [comment]
I've had a go at making this change, as it's Hacktoberfest and I'm fairly new to open source contribution. Please see PR available here: https://github.com/codingo/Reconnoitre/pull/49

**Comment by codingo** [comment]
Closed in #49
