### ISSUE TITLE
Small issue when same service is running on multiple port

### ISSUE THREAD

**Issue by cwaazywabbit** [codingo/Reconnoitre#38]
Hi,

when there is a i.e. Webserver running on multiple ports (i.e. 80, 81, 82, 8080..) then according to the current _config.json_, the generated commands would overwrite each other. Better add the port to the file name as well.

![unbenannt](https://user-images.githubusercontent.com/6714156/41909108-78591ab0-7946-11e8-8106-e4c488ca1aff.PNG)

**Comment by cwaazywabbit** [comment]
The fix is ready, will make a pull request as soon as you merge #39.

**Comment by codingo** [comment]
#39 has now been merged, feel free to raise a pull request at your convenience @cwaazywabbit

**Comment by cwaazywabbit** [comment]
The fix was actually sent in the same recent pull request and is now merged. You can confirm and close. Regards
