### ISSUE TITLE
Incorrect path to gobuster wordlists in config.json

### ISSUE THREAD

**Issue by john65** [codingo/Reconnoitre#41]
The gobuster wordlists are at Web_Content, but config.json has Web-Content 
<snip>
"gobuster -w /usr/share/seclists/Discovery/Web-Content/common.txt -u http://$ip:$port/ -s '200,204,301,302,307,403,500' -e | tee '$outputdir/$ip_$port_gobuster_common.txt'",
            "gobuster -w /usr/share/seclists/Discovery/Web-Content/CGIs.txt -u http://$ip:$port/ -s '200,204,301,307,403,500' -e | tee '$outputdir/$ip_$port_gobuster_cgis.txt'"
<snip>

**Comment by codingo** [comment]
This was updated to match the latest SecLists update (https://github.com/danielmiessler/SecLists/tree/master/Discovery). If you update your SecLists to the latest version then your pathing will be correct.
