### ISSUE TITLE
TypeError: bytes-like object required for parsing scan output

### ISSUE THREAD

**Issue by yvonneKim** [codingo/Reconnoitre#45]
Every instance where `lines = results.split("\n")` is called, the following error is thrown: 

`TypeError: a bytes-like object is required, not 'str'`

**Comment by yvonneKim** [comment]
I'm going to make a PR that should fix this issue. It's very quick.

**Comment by codingo** [comment]
@yvonneKim that's excellent, thank-you. Will tag this up for #hacktoberfest for you also.

**Comment by codingo** [comment]
Closed in #46
