### ISSUE TITLE
Creation of Setup.py

### ISSUE THREAD

**Issue by codingo** [codingo/Reconnoitre#55]
This project lacks a proper setup function, You can see how this can work based on the vhostscan repository (https://github.com/codingo/VHostScan).

Leaving tagged for hacktoberfest, will resolve in November if unclaimed.

**Comment by iGeekuPlay** [comment]
@codingo what are you trying to achieve by having this setup.py?

**Comment by codingo** [comment]
@iGeekuPlay see https://github.com/codingo/VHostScan for an example of what I'm trying to do in this particular project also.
