### ISSUE TITLE
"List of Recommended Tools" thread by g0tmilk - link? 

### ISSUE THREAD

**Issue by mathurin68** [codingo/Reconnoitre#89]
Hey guys, great tool, working on the OSCP!  At the bottom of the page you mentioned "List of Recommended Tools" thread by g0tmilk, but I can't find it.  Tons of great stuff on g0tmilk's blog but I can't find the list, can you direct me it?  

Thanks!

**Comment by codingo** [comment]
@mathurin68, you can find this in the OSCP forums once you've signed up for the course. It's not public, so I can't link it here.
