### ISSUE TITLE
Reconnoitre hangs on a simple scan, throws no errors, and does nothing

### ISSUE THREAD

**Issue by jeffreygray** [codingo/Reconnoitre#97]
I ran this code present in the Reconnoitre readme:

https://i.imgur.com/KDboodL.png

This is a standard Kali install with other dependencies installed. Any idea why there are no errors whatsoever yet this does not work? See my successful manual nmap below in tmux.

**Comment by jeffreygray** [comment]
To clarify, this is a stock Kali install with a stock install of Reconnoitre using the instructions provided in readme.md

**Comment by codingo** [comment]
Hi @jeffreygray, not ignoring this but other projects are stealing priority. I have reconnoitre on the list for a full overhaul this year, but it may not happen until Hacktoberfest comes around.

**Comment by codingo** [comment]
Hi @jeffreygray , #74 will improve on this, but for now you can modify the nmap scan that is running from `service_scan.py`. The scans in place were tested for use on the OSCP/HTB, but also have room for improvement. The intention of a tool like this one (being build for a lab) is to be educational in nature for the user, but which should also be tailored by the user.

For that reason the suggestions that come back, and the nmap scan that have run aren't continually improved upon, as it's up to the student to understand what is happening to then make those improvements.

If you get stuck changing the scan to suit something that better suits your needs feel free to dm me on twitter (@codingo_) and I'll walk you through it.
